# SPDX-FileCopyrightText: Contributors to the Cable Thermal Model project
#
# SPDX-License-Identifier: MPL-2.0

sonar.projectKey=Alliander_cable-thermal-model
sonar.organization=digitalisering

sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=\
  **/tests/**, \
  **/docs/**, \

# Disable rules for TODOs and variable naming
sonar.issue.ignore.multicriteria.e1.ruleKey=python:S117
sonar.issue.ignore.multicriteria.e2.ruleKey=python:S1135
