# SPDX-FileCopyrightText: Contributors to the Cable Thermal Model project
#
# SPDX-License-Identifier: MPL-2.0

from typing import Generic, TypeVar

from pydantic import BaseModel, ConfigDict, Field, field_validator

from cable_thermal_model.model.cables.enum_classes_cable import CableLayer
from cable_thermal_model.model.schemas.state_schemas import StateAir, StateSoil, StateT

ModelRunOptionsT = TypeVar("ModelRunOptionsT", bound="ModelRunOptions")


class ModelRunOptions(BaseModel, Generic[StateT]):
    """Base run-time options shared by all model types."""

    model_config = ConfigDict(extra="forbid")

    temperature_dependent_electric_resistance: bool = Field(
        default=True,
        description="Whether to let the electric resistance of materials be temperature dependent.",
    )
    ac_current: bool = Field(
        default=True,
        description=(
            "Whether to use an AC current. If True, the model will account for AC conductor "
            "(skin effect, proximity effect) resistance, screen losses and dielectric losses."
        ),
    )
    neglect_dielectric_loss: bool = Field(
        default=False,
        description=(
            "Whether to neglect dielectric loss in the model. "
            "If True, the model will not account for the heat generated by dielectric losses in the cable insulation."
        ),
    )
    extra_solution_layers: tuple[CableLayer, ...] = Field(
        default_factory=tuple,
        description="Additional cable layers to include in the returned result for this run.",
    )

    @field_validator("extra_solution_layers", mode="after")
    @classmethod
    def _deduplicate_extra_solution_layers(
        cls,
        extra_solution_layers: tuple[CableLayer, ...],
    ) -> tuple[CableLayer, ...]:
        """Preserve request order while removing duplicate layers."""
        return tuple(dict.fromkeys(extra_solution_layers))

    @field_validator("extra_solution_layers", mode="after")
    @classmethod
    def _validate_extra_solution_layers_exclude_standard_layers(
        cls,
        extra_solution_layers: tuple[CableLayer, ...],
    ) -> tuple[CableLayer, ...]:
        """Reject layers that already have dedicated extraction logic in model output."""
        disallowed_layers = {CableLayer.Conductor, CableLayer.Sheath, CableLayer.Pipe}
        invalid_layers = tuple(layer for layer in extra_solution_layers if layer in disallowed_layers)
        if invalid_layers:
            invalid_layers_str = ", ".join(layer.value for layer in invalid_layers)
            raise ValueError(f"extra_solution_layers must not include standard result layers: {invalid_layers_str}.")

        return extra_solution_layers


class ModelSoilRunOptions(ModelRunOptions[StateSoil]):
    """Run-time options for the soil model, extending ModelRunOptions with soil-drying support."""

    soil_drying: bool = Field(
        default=False,
        description="Whether to let soil dry out around cables due to cable heating.",
    )


class ModelAirRunOptions(ModelRunOptions[StateAir]):
    """Run-time options for the air model; no additional options beyond the base class."""

    pass
